// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestProject.Models;

namespace TestProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220806164023_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TestProject.Models.Account", b =>
                {
                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IncedentName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AccountName");

                    b.HasIndex("AccountName")
                        .IsUnique();

                    b.HasIndex("IncedentName");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("TestProject.Models.Contact", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstNme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.HasIndex("AccountName");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("TestProject.Models.Incedent", b =>
                {
                    b.Property<string>("IncedentName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IncedentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IncedentName");

                    b.ToTable("Incedents");
                });

            modelBuilder.Entity("TestProject.Models.Account", b =>
                {
                    b.HasOne("TestProject.Models.Incedent", null)
                        .WithMany("Accounts")
                        .HasForeignKey("IncedentName");
                });

            modelBuilder.Entity("TestProject.Models.Contact", b =>
                {
                    b.HasOne("TestProject.Models.Account", null)
                        .WithMany("Contacts")
                        .HasForeignKey("AccountName");
                });

            modelBuilder.Entity("TestProject.Models.Account", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("TestProject.Models.Incedent", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
